apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: ose-gitops-ahx
  namespace: ose-gitops-ahx
  finalizers:
    - argoproj.io/finalizer
  labels:
    app.kubernetes.io/instance: openshift-gitops-custom-instances-app
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  server:
    autoscale:
      enabled: false
    enableRolloutsUI: true
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    insecure: true
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
    route:
      enabled: true
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  monitoring:
    enabled: false
  notifications:
    enabled: true
    logLevel: warn
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
    provider: dex
  applicationSet:
    resources:
      limits:
        cpu: 250m
        memory: 5Gi
      requests:
        cpu: 50m
        memory: 512Mi
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  rbac:
    defaultPolicy: 'role:'''''
    policy: |
      g, BD-OpenShift-Cluster-Project-Admin-paasu, role:admin
      g, BD-OpenShift-Cluster-Admin-paasu, role:readonly
    scopes: '[groups]'
  extraConfig:
    resource.customizations.ignoreResourceUpdates.all: |
      jsonPointers:
      - /status
    resource.ignoreResourceUpdatesEnabled: 'true'
  repo:
    logLevel: warn
    replicas: 3
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 256Mi
    serviceaccount: ose-argocd-ahx
  ha:
    enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
  tls:
    ca: {}
  redis:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
  controller:
    logLevel: warn
    processors:
      operation: 50
      status: 100
    resources:
      limits:
        cpu: '1'
        memory: 20Gi
      requests:
        cpu: 100m
        memory: 5Gi
    sharding: {}
