apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: ose-gitops-ahx-new
  namespace: ose-gitops-ahx
  finalizers:
    - argoproj.io/finalizer
  labels:
    app.kubernetes.io/instance: ose-gitops-ahx-new
spec:
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
    service:
      type: ''
  resourceTrackingMethod: label
  initialSSHKnownHosts: {}
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
    provider: dex
  applicationInstanceLabelKey: argocd.argoproj.io/instance
  applicationSet:
    resources:
      limits:
        cpu: '2'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |-
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, admin, role:admin
    scopes: '[groups, email]'
  repo:
    initContainers:
      - command:
          - bash
          - '-c'
          - cat /var/run/kube-root-ca/ca.crt /var/run/trusted-ca/ca-bundle.crt /var/run/trusted-hub/hub-kube-root-ca.crt > /tmp/ca-bundles/ca-bundle.crt || true
        image: 'quay.io/hybridcloudpatterns/imperative-container:v1'
        name: fetch-ca
        resources: {}
        volumeMounts:
          - mountPath: /var/run/kube-root-ca
            name: kube-root-ca
          - mountPath: /var/run/trusted-ca
            name: trusted-ca-bundle
          - mountPath: /var/run/trusted-hub
            name: trusted-hub-bundle
          - mountPath: /tmp/ca-bundles
            name: ca-bundles
    resources:
      limits:
        cpu: '1'
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
      - mountPath: /etc/pki/tls/certs
        name: ca-bundles
    volumes:
      - configMap:
          name: kube-root-ca.crt
        name: kube-root-ca
      - configMap:
          name: trusted-ca-bundle
          optional: true
        name: trusted-ca-bundle
      - configMap:
          name: trusted-hub-bundle
          optional: true
        name: trusted-hub-bundle
      - emptyDir: {}
        name: ca-bundles
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      kinds:
      - TaskRun
      - PipelineRun
  resourceHealthChecks:
    - check: |
        hs = {}
        if obj.status == nil then
          hs.status = "Progressing"
          hs.message = "Waiting for the status to be reported"
          return hs
        end

        -- A policy will not have a compliant field but will have a placement key set if
        -- it is not being applied to any clusters
        if obj.status.compliant == nil and #obj.status.placement > 0 then
          hs.status = "Healthy"
          hs.message = "No clusters match this policy"
          return hs
        end

        if obj.status.compliant == nil then
          hs.status = "Progressing"
          hs.message = "Waiting for the status to be reported"
          return hs
        end

        if obj.status.compliant == "Compliant" or obj.status.compliant == "Pending" then
          hs.status = "Healthy"
        else
          hs.status = "Degraded"
        end
        noncompliants = {}
        if obj.status.status ~= nil then
          -- "root" policy
          for i, entry in ipairs(obj.status.status) do
            if entry.compliant ~= "Compliant" then
              table.insert(noncompliants, entry.clustername)
            end
          end
          if #noncompliants == 0 then
            hs.message = "All clusters are compliant"
          else
            hs.message = "NonCompliant clusters: " .. table.concat(noncompliants, ", ")
          end
        elseif obj.status.details ~= nil then
          -- "replicated" policy
          for i, entry in ipairs(obj.status.details) do
            if entry.compliant ~= "Compliant" then
              table.insert(noncompliants, entry.templateMeta.name)
            end
          end
          if #noncompliants == 0 then
            hs.message = "All templates are compliant"
          else
            hs.message = "NonCompliant templates: " .. table.concat(noncompliants, ", ")
          end
        end
        return hs
      group: policy.open-cluster-management.io
      kind: Policy
    - check: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase ~= nil then
            if obj.status.phase == "Pending" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            elseif obj.status.phase == "Bound" then
              hs.status = "Healthy"
              hs.message = obj.status.phase
              return hs
            end
          end
        end
        hs.status = "Progressing"
        hs.message = "Waiting for PVC"
        return hs
      kind: PersistentVolumeClaim
    - check: |
        local health_status = {}

        health_status.status = "Progressing"
        health_status.message = "Waiting for InferenceService to report status..."

        if obj.status ~= nil then

          local progressing = false
          local degraded = false
          local status_false = 0
          local status_unknown = 0
          local msg = ""

          if obj.status.modelStatus ~= nil then
            if obj.status.modelStatus.transitionStatus ~= "UpToDate" then
              if obj.status.modelStatus.transitionStatus == "InProgress" then
                progressing = true
              else
                degraded = true
              end
              msg = msg .. "0: transitionStatus | " .. obj.status.modelStatus.transitionStatus
            end
          end

          if obj.status.conditions ~= nil then
            for i, condition in pairs(obj.status.conditions) do

              if condition.status == "Unknown" then
                status_unknown = status_unknown + 1
              elseif condition.status == "False" then
                status_false = status_false + 1
              end

              if condition.status ~= "True" then
                msg = msg .. " | " .. i .. ": " .. condition.type .. " | " .. condition.status
                if condition.reason ~= nil and condition.reason ~= "" then
                  msg = msg .. " | " .. condition.reason
                end
                if condition.message ~= nil and condition.message ~= "" then
                  msg = msg .. " | " .. condition.message
                end
              end

            end

            if progressing == false and degraded == false and status_unknown == 0 and status_false == 0 then
              health_status.status = "Healthy"
              msg = "InferenceService is healthy."
            elseif degraded == false and status_unknown >= 0 then
              health_status.status = "Progressing"
            else
              health_status.status = "Degraded"
            end

            health_status.message = msg
          end
        end

        return health_status
      group: serving.kserve.io
      kind: InferenceService
  tls:
    ca: {}
  controller:
    processors: {}
    resources:
      limits:
        cpu: '4'
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 2Gi

---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: ose-gitops-ahx
  namespace: ose-gitops-ahx
  finalizers:
    - argoproj.io/finalizer
  labels:
    app.kubernetes.io/instance: openshift-gitops-custom-instances-app
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  server:
    autoscale:
      enabled: false
    enableRolloutsUI: true
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    insecure: true
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 1Gi
    route:
      enabled: true
    service:
      type: ''
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  monitoring:
    enabled: false
  notifications:
    enabled: true
    logLevel: warn
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  initialSSHKnownHosts: {}
  sso:
    dex:
      openShiftOAuth: true
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
    provider: dex
  applicationSet:
    resources:
      limits:
        cpu: 250m
        memory: 5Gi
      requests:
        cpu: 50m
        memory: 512Mi
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  rbac:
    defaultPolicy: 'role:'''''
    policy: |
      g, BD-OpenShift-Cluster-Project-Admin-paasu, role:admin
      g, BD-OpenShift-Cluster-Admin-paasu, role:readonly
    scopes: '[groups]'
  extraConfig:
    resource.customizations.ignoreResourceUpdates.all: |
      jsonPointers:
      - /status
    resource.ignoreResourceUpdatesEnabled: 'true'
  repo:
    logLevel: warn
    replicas: 3
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: 50m
        memory: 256Mi
    serviceaccount: ose-gitops-ahx
  ha:
    enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
  tls:
    ca: {}
  redis:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
  controller:
    logLevel: warn
    processors:
      operation: 50
      status: 100
    resources:
      limits:
        cpu: '1'
        memory: 20Gi
      requests:
        cpu: 100m
        memory: 5Gi
    sharding: {}
