kind: Secret
apiVersion: v1
metadata:
  name: in-cluster
  namespace: ose-gitops-ahx
  labels:
    argocd.argoproj.io/secret-type: cluster
data:
  config: cccccc=
  name: cdccc==
  server: dfdfdffffd
type: Opaque
