kind: ServiceAccount
apiVersion: v1
metadata:
  name: ose-gitops-ahx
  namespace: ose-gitops-ahx
  labels:
    app.kubernetes.io/instance: openshift-gitops-custom-instances-app
  annotations:
    argocd.argoproj.io/sync-wave: "5"
